<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>Morali</RootNamespace>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
        <UserSecretsId>cc3b5a8e-f9e3-47f9-a512-54685718fdf0</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.10">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Morali.Application\Morali.Application.csproj" />
      <ProjectReference Include="..\Morali.Infrastructure\Morali.Infrastructure.csproj" />
    </ItemGroup>

</Project>
